apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  istio_namespace: istio-system
  auth:
    strategy: openshift
  deployment:
    logger:
      log_level: info
    view_only_mode: false
    cluster_wide_access: true
    accessible_namespaces:
      - "**"
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: 'false'
    custom_secrets:
      - name: cacert
        mount: "/kiali-trace-cert"
        optional: false
  external_services:
    grafana:
      enabled: false
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      query_scope:
        mesh_id: ossm-3
      thanos_proxy:
        enabled: true
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    tracing:
      enabled: true
      provider: tempo
      use_grpc: false
      internal_url: "https://tempo-sample-gateway.tracing-system.svc.cluster.local:8080/api/traces/v1/north/tempo"
      external_url: https://tempo-sample-gateway-tracing-system.apps.cluster-fhr9p.fhr9p.sandbox72.opentlc.com/api/traces/v1/north/search
      health_check_url: https://tempo-sample-gateway-tracing-system.apps.cluster-fhr9p.fhr9p.sandbox72.opentlc.com/api/traces/v1/north/tempo/api/echo
      auth: 
        ca_file: "/kiali-trace-cert/ca.crt"
        insecure_skip_verify: false
        type: bearer
        use_kiali_token: true
      query_timeout: 60
      tempo_config:
        url_format: "jaeger"
  installation_tag: "Kiali [istio-system]"
  server:
    write_timeout: 60