---
- name: Install Operators from OperatorHub
  hosts: localhost
  gather_facts: no

  vars:
    subscriptions_file: "./resources/subscriptions.yaml"
    namespace: "openshift-operators"
    operators:
      - "servicemesh-operator3"
      - "kiali-operator"
      - "opentelemetry-operator"
      - "tempo-operator"

  tasks:
    - name: Apply subscriptions YAML file
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', subscriptions_file) }}"

    - name: Wait for operators to be running
      block:
        - name: Check if operator pod is running
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Pod
            namespace: "{{ namespace }}"
          register: pods_info
          until: "item.metadata.name in pods_info.resources | selectattr('status.phase', 'equalto', 'Running') | map(attribute='metadata.name') | list"
          with_items: "{{ operators }}"
          retries: 20
          delay: 10

    - name: Display success message
      debug:
        msg: "All operators were installed successfully"

    - name: Get pods in the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
      register: pods_list

    - name: Display pods
      debug:
        var: pods_list.resources
